default_config:

# Steps to reduce Write Cycles and extend SD/SSD life expectancy
# https://community.home-assistant.io/t/steps-to-reduce-write-cycles-and-extend-sd-ssd-life-expectancy/291718
logger:
  default: critical
  #default: debug
  logs:
    # log level for HA core
    homeassistant.core: fatal
    #homeassistant.core: debug
recorder:
  #db_url: "sqlite:///:memory:" // If enabled, only memory is used so on a reboot everything is lost
  commit_interval: 30 # Data will be persisted to database every 60 seconds
  purge_keep_days: 7
  exclude:
    domains: # List of all domains: https://community.home-assistant.io/t/where-can-i-find-a-list-of-domains/62654
      - media_player
    entities:
      - sensor.hacs
    entity_globs:
      - sensor.pixel*
      - sun*
      - weather*

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 500
  unit_system: imperial
  time_zone: America/Chicago
  currency: USD
  country: US
  external_url: !secret external_url
  packages: !include_dir_named packages

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

panel_custom:
  - name: ha_server_con
    sidebar_title: Server Controls
    sidebar_icon: mdi:cog-transfer
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/server_control"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
  - name: ha_automations
    sidebar_title: Automations
    sidebar_icon: mdi:robot
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/automation/dashboard"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
  - name: ha_scripts
    sidebar_title: Scripts
    sidebar_icon: mdi:script-text-play
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/script/dashboard"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
  - name: ha_scenes
    sidebar_title: Scenes
    sidebar_icon: mdi:palette
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/scene/dashboard"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator    
  - name: ha_integ
    sidebar_title: Integrations
    sidebar_icon: mdi:checkerboard
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/integrations"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

ifttt:
  key: !secret ifttt_key

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

google_assistant:
  project_id: home-assistant-86f18
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - switch
    - light
    - input_boolean
    - scene
    - sensor
    - climate
  entity_config:
    # Scenes must be assigned to a room to be available to other secondary users
    scene.dinner:
      room: Kitchen
    sensor.main_thermostat_humidity:
      expose: false
    sensor.main_thermostat_temperature:
      expose: false
    sensor.basement_thermostat_humidity:
      expose: false
    sensor.basement_thermostat_temperature:
      expose: false
    sensor.universal_electronics_inc_urc4460bc0_x_r_temperature:
      expose: false
    sensor.brady_pixel_3_battery_temperature:
      expose: false
    sensor.katie_pixel_3_battery_temperature:
      expose: false
   
switch:
  - platform: template
    switches:
      alarm_armed_away:
        friendly_name: Alarm Armed Away
        value_template: "{{ is_state('alarm_control_panel.lyricaiod74830', 'armed_away') }}"
        turn_on:
          service: alarm_control_panel.alarm_arm_away
          data:
            entity_id: alarm_control_panel.lyricaiod74830
        turn_off:
          service: alarm_control_panel.alarm_disarm
          data:
            entity_id: alarm_control_panel.lyricaiod74830
      tv_mute_switch:
        friendly_name: TV Mute Switch
        value_template: "{{ states.media_player.tv.attributes.is_volume_muted }}"
        turn_on:
          service: media_player.volume_mute
          data:
            entity_id: media_player.tv
            is_volume_muted: true
        turn_off:
          service: media_player.volume_mute
          data:
            entity_id: media_player.tv
            is_volume_muted: false
      roku_pause_switch:
        friendly_name: Roku Pause Switch
        value_template: "{{ is_state('media_player.roku_ultra', 'paused') }}"
        turn_on:
          service: media_player.media_pause
          data:
            device_id: d8b259214bd2acefdc70dae49649ef45
        turn_off:
          service: media_player.media_play
          data:
            device_id: d8b259214bd2acefdc70dae49649ef45
      roku_find_remote:
        friendly_name: Roku Find Remote
        value_template: >
          {% if is_state('switch.roku_find_remote','on') %}
            false
          {% endif %}
        turn_on:
          service: remote.send_command
          target:
            entity_id: remote.roku_ultra
          data:
            command: find_remote
        turn_off:
        
input_boolean:
  baby_sitter_mode:
    name: Babysitter Mode
    icon: mdi:baby
  no_school_tomorrow_mode:
    name: No School Tomorrow Mode
    icon: mdi:cancel
group:
  presence_home:
    name: Presence Home
    entities:
      - person.brady
      - person.katie
      
notify:
  - name: all_phones
    platform: group
    services:
      - service: mobile_app_bradys_iphone
      - service: mobile_app_katie_pixel_4a
  - name: katie_phone
    platform: group
    services:
      - service: mobile_app_katie_pixel_4a

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#spotify:
#  client_id: !secret spotify_client_id
#  client_secret: !secret spotify_client_secret
